# Generated by Django 3.1.3 on 2020-11-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageservicestatus',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='post_id, etc'),
        ),
        migrations.AddField(
            model_name='messageservicestatus',
            name='posted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
